# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [23]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [24]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.10353747 0.01005781 0.93753238 ... 0.08376598 0.83134221 0.23785024]
 [0.01229395 0.2986222  0.21362612 ... 0.1496257  0.63452185 0.55582299]
 [0.86830177 0.94241416 0.2482275  ... 0.93717603 0.27566812 0.12267936]
 ...
 [0.70350433 0.97889932 0.88960243 ... 0.15717917 0.07642876 0.59790484]
 [0.69581196 0.76026685 0.67053602 ... 0.83727256 0.47216399 0.81613692]
 [0.11023739 0.41366701 0.87247423 ... 0.16336798 0.16710949 0.46852084]]
[[0.88210611 0.27539217 0.48399611 ... 0.42668964 0.24733433 0.6791698 ]
 [0.16415082 0.97360486 0.03060613 ... 0.38560735 0.37596716 0.25613642]
 [0.77151851 0.68635104 0.27887792 ... 0.11808794 0.78102368 0.02753424]
 ...
 [0.29093612 0.48697443 0.50440212 ... 0.20519404 0.06374533 0.80906492]
 [0.62598205 0.95147684 0.63279481 ... 0.99844768 0.68126112 0.64983008]
 [0.17443578 0.2949202  0.87203602 ... 0.12483154 0.80402751 0.57212998]]


Без использования numpy

In [25]:
def mult(a, b):
    result = [[0 for x in range(len(a))] for y in range(len(b[0]))]
    for i in range(len(a)):
      for j in range(len(b[0])):
        for k in range(len(b)):
          result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [26]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [27]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: total: 250 ms
Wall time: 797 ms


In [28]:
%%time
# засечем время работы функции c NumPy
M2 = np_mult(a, b)

CPU times: total: 0 ns
Wall time: 1.01 ms


In [29]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.369215851809713e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [30]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.61176948 0.26711492 0.64956426] [0.03328659 0.03699138 0.57313091]


In [31]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [32]:
def np_scalar_product(a,b):
    return np.dot(a, b)

In [33]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: total: 0 ns
Wall time: 0 ns
CPU times: total: 0 ns
Wall time: 0 ns


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Значительная часть логики numpy написана на C, поэтому выполнение векторных операций происходит на порядок быстрее.

------------------

### Задание 3
Напишите функцию, которая находит сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [34]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diag = np.diag(a)
    even_diag = diag[diag % 2 == 0]
    if len(even_diag) == 0:
        return 0
    return np.sum(even_diag)

In [35]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 4, 7, 9, 6],
       [4, 6, 9, 2, 9],
       [7, 2, 4, 9, 4],
       [3, 5, 2, 9, 6],
       [2, 8, 2, 9, 1]])

In [36]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: total: 0 ns
Wall time: 0 ns


16

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [37]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumsum = np.cumsum(X, axis=1)
    row_indices = np.arange(1, X.shape[1] + 1)
    result = cumsum / row_indices[:, np.newaxis]
    return result

In [38]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[9.82778714e-01 3.33082784e-01 4.39968116e-01 7.51060617e-01
 3.24908634e-01 9.93191512e-01 3.50394182e-01 4.27497720e-01
 2.79345710e-02 9.15261287e-01 7.12996776e-03 4.42687711e-01
 1.07274757e-01 3.27016538e-01 4.52314121e-01 3.99543596e-01
 5.91842882e-01 3.21634351e-01 1.53317042e-01 1.87955686e-01
 9.81227412e-01 5.03010844e-01 1.38300479e-01 5.21443121e-01
 2.82547857e-01 9.87382187e-01 2.96979359e-01 3.01201870e-01
 5.59168630e-01 8.76673245e-01 4.68691954e-01 3.78361527e-01
 8.35724985e-01 1.45944123e-01 4.07796680e-01 5.80932663e-01
 3.91099746e-01 9.65552183e-01 6.91995519e-01 8.60480719e-01
 4.33954008e-01 7.80266926e-01 4.59408226e-01 2.65512918e-01
 7.04408622e-01 4.10369315e-01 9.66980497e-01 5.37806531e-01
 7.43978080e-01 4.06312219e-01 3.61313237e-01 9.17442925e-01
 9.44635603e-01 7.89182019e-01 1.72610030e-01 1.02543028e-01
 3.69602590e-01 8.65536215e-01 2.05835052e-01 5.78901918e-01
 2.05484493e-01 8.03726656e-01 1.02773599e-01 5.22039760e-01
 8.66594631e-01 7.367218

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [39]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = []
    count = 1
    for i in range(1, len(a)):
        if a[i] == a[i-1]:
            count += 1
        else:
            result.append(a[i-1])
            result.append(count)
            count = 1
    result.append(a[-1])
    result.append(count)

    return np.array(result[0::2]), np.array(result[1::2])

In [40]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(x,num)

CPU times: total: 0 ns
Wall time: 0 ns
[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [41]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    X_copy = np.copy(X)
    X_copy[1::2] = a
    X_copy[::2] = np.power(X_copy[::2], 3)
    result = np.concatenate((X, X_copy[::-1]))
    return result

In [42]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(S2)

CPU times: total: 0 ns
Wall time: 1.07 ms
[  1   3   5   7   9 729   5 125   5   1]
